admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

gfct:
    resource: "@GfctBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /usuarios/logout
