gfct_homepage:
    path:     /
    defaults: { _controller: GfctBundle:Default:index }

all_empresa:
    path:     /empresa/all
    defaults: { _controller: GfctBundle:Empresa:all }

nueva_empresa:
    path:     /empresa/new
    defaults: { _controller: GfctBundle:Empresa:new }
