gfct_homepage:
    path:     /
    defaults: { _controller: GfctBundle:Default:index }

all_empresa:
    path:     /empresa/all
    defaults: { _controller: GfctBundle:Empresa:all }

all_alumno:
    path:     /alumno/all
    defaults: { _controller: GfctBundle:Alumno:all }

all_profesores:
    path:     /profesor/all
    defaults: { _controller: GfctBundle:Profesores:all }

nueva_empresa:
    path:     /empresa/new
    defaults: { _controller: GfctBundle:Empresa:new }

nuevo_profesor:
    path:     /profesor/new
    defaults: { _controller: GfctBundle:Profesores:new }    

jsonRespuesta:
    path:     /empresa
    defaults: { _controller: GfctBundle:EmpresaApi:JSON }
    methods:  [GET]
